2020年卒修士・学士の論文リストを作成した
KatLab-MiyazakiUniv/WebPage pull request #32
Opened 2020-03-30 14:13 UTC by Oiwane

暇だったので追加してみました。

正しく変更されているかの確認、よろしくです。

2020-03-30 14:23 UTC, SatoshiTanoue commented
LGTM

2020-03-30 14:42 UTC, korosuke613 approved these changes
Looks Good To Me!

2020-04-09 03:04 UTC, arimakaoru requested changes

2020-04-09 03:04 UTC, arimakaoru commented on html/parts/papers_list/papers2020.php
> +    '保坂 正道'=>array('開発背景の情報を俯瞰的に捉えたコーディング履歴の理解支援ツールProtの試作',''),
五十音順にしてほしい！

2020-04-09 13:11 UTC, Oiwane commented on html/parts/papers_list/papers2020.php
> +    '保坂 正道'=>array('開発背景の情報を俯瞰的に捉えたコーディング履歴の理解支援ツールProtの試作',''),
しました～

2020-04-09 13:47 UTC, arimakaoru approved these changes
👍🏼

2020-04-09 13:50 UTC, merged